import pandas
import openpyxl
data = pandas.read_excel("Pooled YM integral data.xlsx", engine="openpyxl")
grp = data.groupby(["Drug","Transfection","[DOX]"])
means = grp.mean()
sems = grp.sem()
ns = grp.count()
combi = means.join(sems, lsuffix = " Mean", rsuffix = " SEM")
combi = combi.join(ns)
combi = combi.drop(columns = ["Date","Log[drug]"])
combi = combi.rename(columns={"AUC (RFU*s) Mean":"Mean", "AUC (RFU*s) SEM":"SEM", "AUC (RFU*s)":"N"})
combi = combi.unstack("Transfection")
combi = combi.swaplevel(i = 0, j = 1, axis = 1)
combi = combi.sort_values(by = "Transfection", ascending = False, axis = 1)
combi = combi.reindex(["Mean","SEM","N"], axis = 1, level = 1)
combi.to_excel("YM Integral statistics.xlsx")
data = pandas.read_excel("Pooled YM peak data.xlsx", engine="openpyxl")
grp = data.groupby(["Drug","Transfection","[DOX]"])
means = grp.mean()
sems = grp.sem()
ns = grp.count()
combi = means.join(sems, lsuffix = " Mean", rsuffix = " SEM")
combi = combi.join(ns)
combi = combi.drop(columns = ["Date","Log[drug]"])
combi = combi.rename(columns={"Peak (RFU) Mean":"Mean", "Peak (RFU) SEM":"SEM", "Peak (RFU)":"N"})
combi = combi.unstack("Transfection")
combi = combi.swaplevel(i = 0, j = 1, axis = 1)
combi = combi.sort_values(by = "Transfection", ascending = False, axis = 1)
combi = combi.reindex(["Mean","SEM","N"], axis = 1, level = 1)
combi.to_excel("YM Peak statistics.xlsx")
data = pandas.read_excel("Pooled PTX integral data.xlsx", engine="openpyxl")
data = data[~(data.Date.isin([22321, 22621]))]
grp = data.groupby(["Drug","Transfection","[DOX]"])
means = grp.mean()
sems = grp.sem()
ns = grp.count()
combi = means.join(sems, lsuffix = " Mean", rsuffix = " SEM")
combi = combi.join(ns)
combi = combi.drop(columns = ["Date","Log[drug]"])
combi = combi.rename(columns={"AUC (RFU*s) Mean":"Mean", "AUC (RFU*s) SEM":"SEM", "AUC (RFU*s)":"N"})
combi = combi.unstack("Transfection")
combi = combi.swaplevel(i = 0, j = 1, axis = 1)
combi = combi.sort_values(by = "Transfection", ascending = False, axis = 1)
combi = combi.reindex(["Mean","SEM","N"], axis = 1, level = 1)
combi.to_excel("PTX Integral statistics.xlsx")
data = pandas.read_excel("Pooled PTX peak data.xlsx", engine="openpyxl")
data = data[~(data.Date.isin([22321, 22621]))]
grp = data.groupby(["Drug","Transfection","[DOX]"])
means = grp.mean()
sems = grp.sem()
ns = grp.count()
combi = means.join(sems, lsuffix = " Mean", rsuffix = " SEM")
combi = combi.join(ns)
combi = combi.drop(columns = ["Date","Log[drug]"])
combi = combi.rename(columns={"Peak (RFU) Mean":"Mean", "Peak (RFU) SEM":"SEM", "Peak (RFU)":"N"})
combi = combi.unstack("Transfection")
combi = combi.swaplevel(i = 0, j = 1, axis = 1)
combi = combi.sort_values(by = "Transfection", ascending = False, axis = 1)
combi = combi.reindex(["Mean","SEM","N"], axis = 1, level = 1)
combi.to_excel("PTX Peak statistics.xlsx")