import pandas
import openpyxl
data = pandas.read_excel("Pooled dose response integral data.xlsx", engine="openpyxl")
data = data[data.Date != 101520]
grp = data.groupby(["Drug","Log[drug]","[DOX]"])
means = grp.mean()
sems = grp.sem()
ns = grp.count()
combi = means.join(sems, lsuffix = " Mean", rsuffix = " SEM")
combi = combi.join(ns)
combi = combi.drop(columns = ["Date","Transfection"])
combi = combi.rename(columns={"AUC (RFU*s) Mean":"Mean", "AUC (RFU*s) SEM":"SEM", "AUC (RFU*s)":"N"})
combi = combi.unstack("[DOX]")
combi = combi.swaplevel(i = 0, j = 1, axis = 1)
combi = combi.sort_values(by = "[DOX]", axis = 1)
combi = combi.reindex(["Mean","SEM","N"], axis = 1, level = 1)
combi.to_excel("Dose response integral statistics.xlsx")
data = pandas.read_excel("Pooled dose response peak data.xlsx", engine="openpyxl")
data = data[data.Date != 101520]
grp = data.groupby(["Drug","Log[drug]","[DOX]"])
means = grp.mean()
sems = grp.sem()
ns = grp.count()
combi = means.join(sems, lsuffix = " Mean", rsuffix = " SEM")
combi = combi.join(ns)
combi = combi.drop(columns = ["Date","Transfection"])
combi = combi.rename(columns={"Peak (RFU) Mean":"Mean", "Peak (RFU) SEM":"SEM", "Peak (RFU)":"N"})
combi = combi.unstack("[DOX]")
combi = combi.swaplevel(i = 0, j = 1, axis = 1)
combi = combi.sort_values(by = "[DOX]", axis = 1)
combi = combi.reindex(["Mean","SEM","N"], axis = 1, level = 1)
combi.to_excel("Dose response peak statistics.xlsx")